const Companies = {
  KVUE: "Kenvue",
  PANW: "Palo Alto Networks",
  AXON: "Axon Enterprise",
  FICO: "Fair Isaac",
  BG: "Bunge Limited",
  PODD: "Insulet",
  GEHC: "GE HealthCare",
  STLD: "Steel Dynamics",
  FSLR: "First Solar",
  ACGL: "Arch Capital Group",
  TRGP: "Targa Resources",
  EQT: "EQT",
  PCG: "PG&E Corporation",
  CSGP: "CoStar Group",
  INVH: "Invitation Homes",
  KDP: "Keurig Dr Pepper",
  ON: "ON Semiconductor",
  VICI: "Vici Properties",
  WBD: "Warner Bros. Discovery",
  CPT: "Camden Property Trust",
  MOH: "Molina Healthcare",
  NDSN: "Nordson Corporation",
  CEG: "Constellation Energy",
  FDS: "FactSet",
  SEDG: "SolarEdge",
  EPAM: "EPAM Systems",
  BRO: "Brown & Brown",
  CDAY: "Ceridian",
  MTCH: "Match Group",
  TECH: "Bio-Techne",
  MRNA: "Moderna",
  OGN: "Organon & Co.",
  CRL: "Charles River Laboratories",
  PTC: "PTC",
  CZR: "Caesars Entertainment",
  GNRC: "Generac",
  NXPI: "NXP Semiconductors",
  MPWR: "Monolithic Power Systems",
  TRMB: "Trimble Inc.",
  ENPH: "Enphase",
  TSLA: "Tesla, Inc.",
  POOL: "Pool Corporation",
  CTLT: "Catalent",
  ETSY: "Etsy",
  TER: "Teradyne",
  BIO: "Bio-Rad",
  TDY: "Teledyne Technologies",
  TYL: "Tyler Technologies",
  WST: "West Pharmaceutical Services",
  DPZ: "Domino's",
  DXCM: "Dexcom",
  CARR: "Carrier Global",
  OTIS: "Otis Worldwide",
  IR: "Ingersoll Rand",
  PAYC: "Paycom",
  LYV: "Live Nation Entertainment",
  STE: "Steris",
  ZBRA: "Zebra Technologies",
  ODFL: "Old Dominion",
  WRB: "Berkley",
  NOW: "ServiceNow",
  LVS: "Las Vegas Sands",
  NVR: "NVR, Inc.",
  CDW: "CDW",
  IEX: "IDEX Corporation",
  LDOS: "Leidos",
  TMUS: "T-Mobile US",
  MKTX: "MarketAxess",
  AMCR: "Amcor",
  CTVA: "Corteva",
  DD: "DuPont",
  DOW: "Dow Inc.",
  WAB: "Wabtec",
  ATO: "Atmos Energy",
  TFX: "Teleflex",
  CE: "Celanese",
  FANG: "Diamondback Energy",
  LW: "Lamb Weston",
  JKHY: "Jack Henry & Associates",
  KEYS: "Keysight",
  FTNT: "Fortinet",
  ROL: "Rollins, Inc.",
  ANET: "Arista Networks",
  CPRT: "Copart",
  FLT: "Fleetcor",
  BR: "Broadridge Financial Solutions",
  EVRG: "Evergy",
  MSCI: "MSCI",
  TTWO: "Take-Two Interactive",
  HII: "Huntington Ingalls Industries",
  NCLH: "Norwegian Cruise Line Holdings",
  CDNS: "Cadence Design Systems",
  SBAC: "SBA Communications",
  IQV: "IQVIA",
  AOS: "A. O. Smith",
  MGM: "MGM Resorts",
  PKG: "Packaging Corporation of America",
  RMD: "ResMed",
  BKR: "Baker Hughes",
  ALGN: "Align Technology",
  ANSS: "Ansys",
  EG: "Everest Re",
  HLT: "Hilton Worldwide",
  IT: "Gartner",
  DXC: "DXC Technology",
  AMD: "AMD",
  ARE: "Alexandria Real Estate Equities",
  RJF: "Raymond James",
  SNPS: "Synopsys",
  REG: "Regency Centers",
  CBOE: "Cboe Global Markets",
  INCY: "Incyte",
  IDXX: "Idexx Laboratories",
  MAA: "Mid-America Apartment Communities",
  COO: "CooperCompanies",
  CHTR: "Charter Communications",
  MTD: "Mettler Toledo",
  ALB: "Albemarle Corporation",
  FTV: "Fortive",
  LNT: "Alliant Energy",
  TDG: "TransDigm Group",
  AJG: "Arthur J. Gallagher & Co.",
  LKQ: "LKQ Corporation",
  DLR: "Digital Realty",
  ALK: "Alaska Air Group",
  GPN: "Global Payments",
  ULTA: "Ulta Beauty",
  CNC: "Centene Corporation",
  HOLX: "Hologic",
  UDR: "UDR, Inc.",
  AWK: "American Water Works",
  FRT: "Federal Realty",
  CFG: "Citizens Financial Group",
  EXR: "Extra Space Storage",
  WTW: "Willis Towers Watson",
  CHD: "Church & Dwight",
  ILMN: "Illumina",
  SYF: "Synchrony Financial",
  HPE: "Hewlett Packard Enterprise",
  VRSK: "Verisk",
  FOX: "Fox Corporation (Class B)",
  NWS: "News Corp (Class B)",
  UAL: "United Airlines Holdings",
  ATVI: "Activision Blizzard",
  PYPL: "PayPal",
  KHC: "Kraft Heinz",
  JBHT: "J.B. Hunt",
  QRVO: "Qorvo",
  O: "Realty Income",
  AAL: "American Airlines Group",
  EQIX: "Equinix",
  HSIC: "Henry Schein",
  SWKS: "Skyworks Solutions",
  HCA: "HCA Healthcare",
  RCL: "Royal Caribbean Group",
  UHS: "Universal Health Services",
  URI: "United Rentals",
  MLM: "Martin Marietta Materials",
  AVGO: "Broadcom Inc.",
  GOOGL: "Alphabet Inc. (Class A)",
  ESS: "Essex Property Trust",
  TSCO: "Tractor Supply",
  META: "Meta Platforms",
  MHK: "Mohawk Industries",
  ALLE: "Allegion",
  AME: "Ametek",
  VRTX: "Vertex Pharmaceuticals",
  DAL: "Delta Air Lines",
  NWSA: "News Corp (Class A)",
  FOXA: "Fox Corporation (Class A)",
  ZTS: "Zoetis",
  GM: "General Motors",
  REGN: "Regeneron",
  ABBV: "AbbVie",
  APTV: "Aptiv",
  GRMN: "Garmin",
  DG: "Dollar General",
  MDLZ: "Mondelez International",
  PNR: "Pentair",
  LYB: "LyondellBasell",
  STX: "Seagate Technology",
  LRCX: "Lam Research",
  MNST: "Monster Beverage",
  KMI: "Kinder Morgan",
  PSX: "Phillips 66",
  CCI: "Crown Castle",
  BWA: "BorgWarner",
  DLTR: "Dollar Tree",
  XYL: "Xylem Inc.",
  TEL: "TE Connectivity",
  MOS: "Mosaic Company (The)",
  ACN: "Accenture",
  MPC: "Marathon Petroleum",
  CMG: "Chipotle Mexican Grill",
  BLK: "BlackRock",
  EW: "Edwards Lifesciences",
  FFIV: "F5, Inc.",
  NFLX: "Netflix",
  TT: "Trane Technologies",
  JCI: "Johnson Controls",
  CB: "Chubb Limited",
  KMX: "CarMax",
  OKE: "ONEOK",
  "BRK-B": "Berkshire Hathaway",
  NRG: "NRG Energy",
  ROP: "Roper Technologies",
  ROST: "Ross Stores",
  V: "Visa Inc.",
  BKNG: "Booking Holdings",
  FMC: "FMC Corporation",
  PWR: "Quanta Services",
  WDC: "Western Digital",
  ORLY: "O'Reilly Auto Parts",
  HRL: "Hormel Foods",
  VTR: "Ventas",
  WELL: "Welltower",
  IRM: "Iron Mountain",
  ES: "Eversource",
  RSG: "Republic Services",
  WYNN: "Wynn Resorts",
  XRAY: "Dentsply Sirona",
  SJM: "J.M. Smucker Company (The)",
  WEC: "WEC Energy Group",
  NDAQ: "Nasdaq, Inc.",
  APH: "Amphenol",
  PXD: "Pioneer Natural Resources",
  LHX: "L3Harris",
  CRM: "Salesforce",
  FAST: "Fastenal",
  CF: "CF Industries",
  IVZ: "Invesco",
  DVA: "DaVita Inc.",
  MA: "Mastercard",
  CTRA: "Coterra",
  ISRG: "Intuitive Surgical",
  PEAK: "Healthpeak",
  PM: "Philip Morris International",
  AMT: "American Tower",
  J: "Jacobs Solutions",
  EXPD: "Expeditors International",
  EXPE: "Expedia Group",
  ICE: "Intercontinental Exchange",
  MCHP: "Microchip Technology",
  AKAM: "Akamai",
  DFS: "Discover Financial",
  AIZ: "Assurant",
  HST: "Host Hotels & Resorts",
  CHRW: "C.H. Robinson",
  RL: "Ralph Lauren Corporation",
  AVB: "AvalonBay Communities",
  CTSH: "Cognizant",
  CBRE: "CBRE Group",
  FIS: "FIS",
  CME: "CME Group",
  JNPR: "Juniper Networks",
  KIM: "Kimco Realty",
  BXP: "Boston Properties",
  GOOG: "Alphabet Inc. (Class C)",
  VRSN: "Verisign",
  EL: "Est\u00e9e Lauder Companies (The)",
  AMZN: "Amazon",
  LEN: "Lennar",
  AMP: "Ameriprise Financial",
  PSA: "Public Storage",
  TSN: "Tyson Foods",
  STZ: "Constellation Brands",
  DHI: "D.R. Horton",
  LH: "LabCorp",
  TPR: "Tapestry, Inc.",
  NaN: "1116132",
  TMO: "Thermo Fisher Scientific",
  GILD: "Gilead Sciences",
  VTRS: "Viatris",
  MTB: "M&T Bank",
  BIIB: "Biogen",
  PLD: "Prologis",
  GEN: "Gen Digital",
  MKC: "McCormick & Company",
  STT: "State Street Corporation",
  VLO: "Valero Energy",
  DGX: "Quest Diagnostics",
  CMCSA: "Comcast",
  TRV: "Travelers Companies (The)",
  ELV: "Elevance Health",
  EA: "Electronic Arts",
  EBAY: "eBay",
  GS: "Goldman Sachs",
  PFG: "Principal Financial Group",
  PRU: "Prudential Financial",
  UPS: "United Parcel Service",
  SPG: "Simon Property Group",
  WAT: "Waters Corporation",
  EQR: "Equity Residential",
  NVDA: "Nvidia",
  PPL: "PPL Corporation",
  ABC: "AmerisourceBergen",
  ZBH: "Zimmer Biomet",
  ZION: "Zions Bancorporation",
  FI: "Fiserv",
  CTAS: "Cintas",
  SRE: "Sempra Energy",
  SYK: "Stryker Corporation",
  MET: "MetLife",
  INTU: "Intuit",
  RHI: "Robert Half",
  EOG: "EOG Resources",
  NI: "NiSource",
  DVN: "Devon Energy",
  SBUX: "Starbucks",
  A: "Agilent Technologies",
  ADI: "Analog Devices",
  PNW: "Pinnacle West",
  QCOM: "Qualcomm",
  VMC: "Vulcan Materials Company",
  BBY: "Best Buy",
  NTAP: "NetApp",
  AFL: "Aflac",
  MCK: "McKesson",
  CCL: "Carnival",
  DHR: "Danaher Corporation",
  AES: "AES Corporation",
  PAYX: "Paychex",
  RF: "Regions Financial Corporation",
  COF: "Capital One",
  MCO: "Moody's Corporation",
  MAR: "Marriott International",
  BEN: "Franklin Templeton",
  NTRS: "Northern Trust",
  OMC: "Omnicom Group",
  CINF: "Cincinnati Financial",
  TFC: "Truist",
  FE: "FirstEnergy",
  YUM: "Yum! Brands",
  KLAC: "KLA Corporation",
  HBAN: "Huntington Bancshares",
  PGR: "Progressive Corporation",
  APA: "APA Corporation",
  EFX: "Equifax",
  SCHW: "Charles Schwab Corporation",
  CAH: "Cardinal Health",
  ADBE: "Adobe Inc.",
  AZO: "AutoZone",
  AON: "Aon",
  FITB: "Fifth Third Bank",
  CMA: "Comerica",
  ALL: "Allstate",
  DRI: "Darden Restaurants",
  L: "Loews Corporation",
  BK: "BNY Mellon",
  AMAT: "Applied Materials",
  GLW: "Corning Inc.",
  BSX: "Boston Scientific",
  PARA: "Paramount Global",
  MU: "Micron Technology",
  LUV: "Southwest Airlines",
  UNH: "UnitedHealth Group",
  MSFT: "Microsoft",
  KEY: "KeyCorp",
  EMN: "Eastman Chemical Company",
  CSCO: "Cisco",
  COST: "Costco",
  MS: "Morgan Stanley",
  IPG: "Interpublic Group of Companies (The)",
  LIN: "Linde plc",
  AMGN: "Amgen",
  AEE: "Ameren",
  ADSK: "Autodesk",
  K: "Kellogg's",
  ORCL: "Oracle Corporation",
  GL: "Globe Life",
  NWL: "Newell Brands",
  ECL: "Ecolab",
  NKE: "Nike, Inc.",
  C: "Citigroup",
  PNC: "PNC Financial Services",
  HD: "Home Depot (The)",
  AVY: "Avery Dennison",
  MMC: "Marsh McLennan",
  SYY: "Sysco",
  MDT: "Medtronic",
  ITW: "Illinois Tool Works",
  PH: "Parker Hannifin",
  DOV: "Dover Corporation",
  TJX: "TJX Companies",
  CNP: "CenterPoint Energy",
  RVTY: "Revvity",
  APD: "Air Products and Chemicals",
  NUE: "Nucor",
  BALL: "Ball Corporation",
  HAS: "Hasbro",
  HES: "Hess Corporation",
  PHM: "PulteGroup",
  LOW: "Lowe's",
  T: "AT&T",
  VZ: "Verizon",
  BBWI: "Bath & Body Works, Inc.",
  CAG: "Conagra Brands",
  AAPL: "Apple Inc.",
  "BF-B": "Brown\u2013Forman",
  SNA: "Snap-on",
  SWK: "Stanley Black & Decker",
  WMT: "Walmart",
  GWW: "W. W. Grainger",
  MAS: "Masco",
  ADP: "ADP",
  FDX: "FedEx",
  PCAR: "Paccar",
  AIG: "American International Group",
  WBA: "Walgreens Boots Alliance",
  VFC: "VF Corporation",
  TXT: "Textron",
  INTC: "Intel",
  TGT: "Target Corporation",
  AXP: "American Express",
  BAC: "Bank of America",
  CI: "Cigna",
  DIS: "Disney",
  DUK: "Duke Energy",
  LNC: "Lincoln Financial",
  NEE: "NextEra Energy",
  TAP: "Molson Coors Beverage Company",
  WFC: "Wells Fargo",
  IFF: "International Flavors & Fragrances",
  JPM: "JPMorgan Chase",
  WMB: "Williams Companies",
  HPQ: "HP Inc.",
  GPC: "Genuine Parts Company",
  JNJ: "Johnson & Johnson",
  BAX: "Baxter International",
  BDX: "Becton Dickinson",
  LLY: "Eli Lilly and Company",
  MCD: "McDonald's",
  NEM: "Newmont",
  CLX: "Clorox",
  CMI: "Cummins",
  EMR: "Emerson Electric",
  SHW: "Sherwin-Williams",
  ABT: "Abbott",
  ADM: "ADM",
  AEP: "American Electric Power",
  BA: "Boeing",
  BMY: "Bristol Myers Squibb",
  CAT: "Caterpillar Inc.",
  CL: "Colgate-Palmolive",
  CMS: "CMS Energy",
  COP: "ConocoPhillips",
  CPB: "Campbell Soup Company",
  CSX: "CSX",
  CVS: "CVS Health",
  CVX: "Chevron Corporation",
  DE: "John Deere",
  DTE: "DTE Energy",
  ED: "Consolidated Edison",
  EIX: "Edison International",
  ETN: "Eaton Corporation",
  ETR: "Entergy",
  EXC: "Exelon",
  F: "Ford Motor Company",
  GD: "General Dynamics",
  GE: "General Electric",
  GIS: "General Mills",
  HAL: "Halliburton",
  HIG: "Hartford (The)",
  HON: "Honeywell",
  HSY: "Hershey's",
  HWM: "Howmet Aerospace",
  IBM: "IBM",
  IP: "International Paper",
  KMB: "Kimberly-Clark",
  KO: "Coca-Cola Company (The)",
  KR: "Kroger",
  LMT: "Lockheed Martin",
  MMM: "3M",
  MO: "Altria",
  MRK: "Merck & Co.",
  MRO: "Marathon Oil",
  MSI: "Motorola Solutions",
  NOC: "Northrop Grumman",
  NSC: "Norfolk Southern Railway",
  OXY: "Occidental Petroleum",
  PEG: "Public Service Enterprise Group",
  PEP: "PepsiCo",
  PFE: "Pfizer",
  PG: "Procter & Gamble",
  PPG: "PPG Industries",
  RTX: "RTX Corporation",
  SEE: "Sealed Air",
  SLB: "Schlumberger",
  SO: "Southern Company",
  SPGI: "S&P Global",
  UNP: "Union Pacific Corporation",
  WRK: "WestRock",
  XEL: "Xcel Energy",
  XOM: "ExxonMobil",
  D: "Dominion Energy",
  FCX: "Freeport-McMoRan",
  HUM: "Humana",
  ROK: "Rockwell Automation",
  TROW: "T. Rowe Price",
  TXN: "Texas Instruments",
  USB: "U.S. Bank",
  WHR: "Whirlpool Corporation",
  WM: "Waste Management",
  WY: "Weyerhaeuser",
};

export default Companies;